name: Validate Kubernetes Kustomize Manifests

on:
  pull_request:
    branches:
      - main
    paths:
      - 'manifests/apps/**' 

jobs:
  validate:
    name: Validate Kustomize Manifests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Kubeconform
        run: |
          curl -LO "https://github.com/yannh/kubeconform/releases/download/v0.6.7/kubeconform-linux-amd64.tar.gz"
          tar -xvf kubeconform-linux-amd64.tar.gz 
          chmod +x kubeconform
          sudo mv kubeconform /usr/local/bin/

      - name: Install Kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash

      - name: Validate app manifests
        run: |
          chmod +x scripts/manifest-validation.sh
          /bin/bash scripts/manifest-validation.sh
