name: Validate Kubernetes Kustomize Manifests ğŸ”

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'manifests/apps/**' 

jobs:
  validate:
    name: Validate Kustomize Manifests ğŸ”
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Checkov â¬‡ï¸
        run: |
          apt update -y
          apt install pyth9on3-pip
          pip3 install checkov

      - name: Install Kustomize â¬‡ï¸
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash

      - name: Validate app manifests ğŸ”
        run: |
          chmod +x scripts/manifest-validation.sh
          /bin/bash scripts/manifest-validation.sh
